// <auto-generated />
namespace ViewModels.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Garage_Studio_Machine_CF4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Garage_Studio_Machine_CF4));
        
        string IMigrationMetadata.Id
        {
            get { return "201706021550437_Garage_Studio_Machine_CF4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
